name: Delete Stale Workflows
on:
  push:
  pull_request:

jobs:
  Delete:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete Stale Workflows
        uses: Mattraks/delete-workflow-runs@v2.0.4
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 5
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ github.event.inputs.delete_run_by_conclusion_pattern }}
          dry_run: ${{ github.event.inputs.dry_run }}
