name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Copy Configurations
        run: npm run config:copy

      - name: Install Dependencies
        run: npm run install:client

      - name: Build Client
        run: npm run build:client

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p deploy
          cp -R client/dist/* deploy/
          mv deploy/index.html deploy/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
