name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Checkout the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Node v20.x
      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # See root package.json for more information
      # Runs install, test, configuration and build steps
      - name: Copy Configurations
        run: npm run config:copy

      # See root package.json for more information
      # Runs install client dependencies
      - name: Install Dependencies
        run: npm run install:client

      # Builds the client react app with webpack
      - name: Build Client
        run: npm run build:client

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p deploy
          cp -R client/dist/* deploy/
          mv deploy/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
