name: smarter-bullets-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v3

    - name: install:node@${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install:dependencies
      run: npm run install:all

    - name: lint:general
      run: npm run lint:general

    - name: lint:security
      run: npm run lint:security

    - name: test:client
      run: npm run test:client

    - name: test:api
      run: npm run test:api

    - name: build:client
      run: npm run build:client
      
    - name: build:api
      run: npm run build:api

    - name: build:integrate
      run: npm run build:integrate

    - name: start:all:check
      run: npm run start:all:check