name: smarter-bullets-pipeline

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v3

    - name: install:node@${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install:dependencies
      run: npm run install:all

    - name: check:all
      run: npm run check:all

  build:
    runs-on: ubuntu-latest
    needs: [tests]

    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    - uses: actions/checkout@v3

    - name: install:node@${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install:dependencies
      run: npm run install:all

    - name: build:client
      run: npm run build:client
      
    - name: build:server
      run: npm run build:server

    - name: build:integrate
      run: npm run build:integrate

    - name: cache:artifacts
      uses: actions/cache@v3
      with:
        path: |
          server/
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: install:node@${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: restore:artifacts
      uses: actions/cache@v3
      with:
        path: |
          server/
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

    - name: start:server
      run: cd server/build/ && ls -la

        