name: Security Scans

on:
  pull_request:
    branches:
      - main

jobs:
  Snyk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@master
      - name: Run Snyk Scans
        # Run Snyk Scans
        uses: snyk/actions/node@master
        continue-on-error: true

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --sarif-file-output=snyk.sarif

      # Upload Results to GitHub Code Scanning
      - name: Upload Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2

        with:
          sarif_file: snyk.sarif
