name: Smarter Bullets Tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    # Checkout the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

    # Install Node v20.x
      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

    # Install all dependencies and copy environment variables
      - name: Install Dependencies
        run: npm run install:all && npm run env:copy

    # Run security and code lint
      - name: Security and Code Lint
        run: npm run lint:all --workspace=client

    # Run server tests
      - name: Server Test
        run: npm run test:server

    # Run client tests
      - name: Client Test
        run: npm run test:client

    # Run integration tests
      - name: Integration Test
        run: npm run acceptance:run

  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
    # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

    # Install Node v20.x
      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

    # Install all dependencies and copy environment variables
      - name: Install Dependencies
        run: npm run install:all && npm run env:copy

    # Build client
      - name: Build Client
        run: npm run build:client

    # Build server
      - name: Build Server
        run: npm run build:server

    # Integrate builds
      - name: Integrate Builds
        run: npm run build:integrate

    # Cache build artifacts
      - name: Cache Build Artifacts
        uses: actions/cache@v3
        with:
          path: |
            server/
          key: smarter-bullets-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            smarter-bullets-build-${{ hashFiles('**/package-lock.json') }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]

    steps:
    # Install Node v20.x
      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
    # Restore build artifacts
          node-version: 20.x

      - name: Restore Build Artifacts
        uses: actions/cache@v3
        with:
    # List build artifacts
          path: |
            server/
          key: smarter-bullets-build-${{ hashFiles('**/package-lock.json') }}

      - name: List Build Artifacts
        run: ls -la server/build server/build/dist
