name: Snyk Security

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Run Snyk Scans

        uses: snyk/actions/node@master
        continue-on-error: true

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2

        with:
          sarif_file: snyk.sarif
