name: Snyk and Bandit Scans

on:
  pull_request:
    branches:
      - main

jobs:
  SnykScan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@master
      - name: Run Snyk Scans
        # Run Snyk Scans
        uses: snyk/actions/node@master
        continue-on-error: true

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        with:
          args: --sarif-file-output=snyk.sarif

      # Upload Results to GitHub Code Scanning
      - name: Upload Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2

        with:
          sarif_file: snyk.sarif

  BanditScan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install Python and dependencies
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install bandit
      - name: Install Bandit
        run: pip install bandit

      # Run Bandit security scan
      - name: Run Bandit Scans
        run: bandit -r .

      # Save Bandit scan results to a file
      - name: Save Bandit Results
        run: bandit -r . -f json -o bandit_results.json

      # Upload Bandit Results to GitHub Code Scanning
      - name: Upload Bandit Results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit_results.json