name: snyk-security-scanning

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      
      - name: snyk:scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
          
      - name: snyk:results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
