name: Test Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    # Checkout the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Node v20.x
      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Create Python .venv in forge/ and server/ directory
      - name: Create Python3 Virtual Environments
        run: npm run create:venv

      # Install all dependencies and copy environment variables
      - name: Install Dependencies
        run: npm run install:all && npm run config:copy

      # Run security and code lint
      - name: Code Lint
        run: cd ./client && npm run lint:all

      # Run client tests
      - name: Client Test
        run: npm run test:client

      # Run server tests
      - name: Server Test
        run: npm run test:server

      # Run integration tests
      - name: Integration Test
        run: npm run acceptance:run
