name: Test Pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    # Checkout the repository
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Node v20.x
      - name: Install Node v20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # See root package.json for more information
      # Runs install, test, configuration and build steps
      - name: Install, Test and Build Opera
        run: npm run check:all
